version: '3.8'

services:
  webapi:
    container_name: elevator_webapi
    build: ./elevator-project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./elevator-project:/usr/src/app
    ports:
      - 8005:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - NUM_CABINS=10
      - NUM_FLOORS=100
