version: '3.8'

services:
  webapi:
    container_name: elevator_webapi
    image: ggnore/elevator_webapi:latest
    build: ./elevator-project
    volumes:
      - ./elevator-project:/usr/src
    ports:
      - 8005:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - NUM_CABINS=10
      - NUM_FLOORS=100
